version: '3'
services:
  registry:
    #image: descartesresearch/teastore-registry
    image: registry.gitlab.com/priam3/teastore/teastore-registry
    expose:
      - "8180"
    depends_on:
      - jaeger
    networks:
      - shared_net
  db:
    #image: descartesresearch/teastore-db
    image: registry.gitlab.com/priam3/teastore/teastore-db
    expose:
      - "3306"
    ports:
      - "3307:3306"
    depends_on:
      - jaeger
    networks:
      - shared_net
  persistence:
    #image: descartesresearch/teastore-persistence
    image: registry.gitlab.com/priam3/teastore/teastore-persistence
    expose:
      - "8180"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
    depends_on:
      - jaeger
    networks:
      - shared_net
  auth:
    #image: descartesresearch/teastore-auth
    image: registry.gitlab.com/priam3/teastore/teastore-auth
    expose:
      - "8180"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
    depends_on:
      - jaeger
    networks:
      - shared_net
  image:
    #image: descartesresearch/teastore-image
    image: registry.gitlab.com/priam3/teastore/teastore-image
    expose:
      - "8180"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
    depends_on:
      - jaeger
    networks:
      - shared_net
  recommender:
    #image: descartesresearch/teastore-recommender
    image: registry.gitlab.com/priam3/teastore/teastore-recommender
    expose:
      - "8180"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
    depends_on:
      - jaeger
    networks:
      - shared_net
  webui:
    #image: descartesresearch/teastore-webui
    image: registry.gitlab.com/priam3/teastore/teastore-webui
    expose:
      - "8180"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    ports:
      - "8180:8080"
    depends_on:
      - jaeger
    networks:
      - shared_net

  cadvisor:
    #image: gcr.io/cadvisor/cadvisor:latest
    image: registry.gitlab.com/priam3/teastore/cadvisor
    ports:
      - "8088:8080"
    networks:
      - shared_net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro

  jaeger:
    #image: jaegertracing/all-in-one:latest
    image: registry.gitlab.com/priam3/teastore/jaeger-tracing
    container_name: jaeger
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - shared_net

networks:
  shared_net:
#    external: true
    name: common_network
