CREATE DATABASE IF NOT EXISTS `priam-actor`;
CREATE DATABASE IF NOT EXISTS `priam-data`;
CREATE DATABASE IF NOT EXISTS `priam-right`;
CREATE DATABASE IF NOT EXISTS `priam-consent`;
CREATE DATABASE IF NOT EXISTS `teadb`;

-- GRANT ALL PRIVILEGES ON 'priam-actor'.* TO 'PRIAM'@'%';
-- GRANT ALL PRIVILEGES ON 'priam-data'.* TO 'PRIAM'@'%';
-- GRANT ALL PRIVILEGES ON 'priam-right'.* TO 'PRIAM'@'%';
-- GRANT ALL PRIVILEGES ON 'teadb'.* TO 'PRIAM'@'%';

-- CREATE USER 'PRIAM'@'%';
-- GRANT ALL PRIVILEGES ON *.* TO 'PRIAM'@'%';