plugins {
    id 'org.springframework.boot' version '2.6.6'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = 'priam.consent'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2021.0.1")
}

dependencies {
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.mapstruct:mapstruct:1.4.2.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'

    implementation 'org.springdoc:springdoc-openapi-ui:1.6.6'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    runtimeOnly 'mysql:mysql-connector-java'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-hateoas'
    implementation 'org.mapstruct:mapstruct:1.4.2.Final'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'io.projectreactor:reactor-core:3.5.0'
    implementation 'mysql:mysql-connector-java:8.0.30'
    //Prometheus
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    implementation 'io.opentelemetry:opentelemetry-exporter-jaeger:1.34.1'
    implementation 'io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter:2.7.0'

    // Downgrade Jackson pour compatibilité avec Springdoc 1.6.6
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.5'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.5'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.5'
 }

	// ⚠ Forcer toutes les dépendances transitives à utiliser Jackson 2.13.5
	configurations.all {
	    resolutionStrategy {
		force 'com.fasterxml.jackson.core:jackson-databind:2.13.5'
		force 'com.fasterxml.jackson.core:jackson-core:2.13.5'
		force 'com.fasterxml.jackson.core:jackson-annotations:2.13.5'
	    }

}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
