"""initial migration

Revision ID: 96da36733178
Revises:
Create Date: 2024-02-12 21:52:59.797686

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96da36733178'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('isAdmin', sa.Boolean(), nullable=False),
        sa.Column('language', sa.Enum('ENGLISH', 'GERMAN', name='language'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'custom_track_field',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'type',
            sa.Enum('STRING', 'INTEGER', 'FLOAT', name='customtrackfieldtype'),
            nullable=True,
        ),
        sa.Column('track_type', sa.Enum('BIKING', 'RUNNING', name='tracktype'), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_required', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'month_goal_count',
        sa.Column('count_minimum', sa.Integer(), nullable=False),
        sa.Column('count_perfect', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('BIKING', 'RUNNING', name='tracktype'), nullable=True),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'month_goal_distance',
        sa.Column('distance_minimum', sa.Integer(), nullable=False),
        sa.Column('distance_perfect', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('BIKING', 'RUNNING', name='tracktype'), nullable=True),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'track',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('BIKING', 'RUNNING', name='tracktype'), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('startTime', sa.DateTime(), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('distance', sa.Integer(), nullable=False),
        sa.Column('averageHeartRate', sa.Integer(), nullable=True),
        sa.Column('elevationSum', sa.Integer(), nullable=True),
        sa.Column('gpxFileName', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'track_info_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'type',
            sa.Enum(
                'DISTANCE',
                'DURATION',
                'SPEED',
                'AVERAGE_HEART_RATE',
                'ELEVATION_SUM',
                name='trackinfoitemtype',
            ),
            nullable=True,
        ),
        sa.Column('is_activated', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_info_item')
    op.drop_table('track')
    op.drop_table('month_goal_distance')
    op.drop_table('month_goal_count')
    op.drop_table('custom_track_field')
    op.drop_table('user')
    # ### end Alembic commands ###
