# Keycloak admin settings
keycloak.admin.server-url=http://keycloak:8080
keycloak.admin.realm=teastore
keycloak.admin.username=admin
keycloak.admin.password=adminpwd
keycloak.admin.client-id=admin-cli