spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: health
          uri: https://http.cat
          predicates:
            - Path=/health
          filters:
            - SetPath=/status/200
        - id: actuator-health
          uri: https://http.cat
          predicates:
            - Path=/actuator/health
          filters:
            - SetPath=/status/200
        - id: data
          uri: http://localhost:8081
          predicates:
            - Path=/data/**
          filters:
            - name: KeycloakLoginCheckFilter
            - RewritePath=/data/(?<segment>.*), /${segment}
        - id: actor
          uri: http://localhost:8082
          predicates:
            - Path=/actor/**
          filters:
            - name: KeycloakLoginCheckFilter
            - RewritePath=/actor/(?<segment>.*), /${segment}
        - id: right
          uri: http://localhost:8083
          predicates:
            - Path=/right/**
          filters:
            - name: KeycloakLoginCheckFilter
            - RewritePath=/right/(?<segment>.*), /${segment}
        - id: cdp
          uri: http://localhost:8089
          predicates:
            - Path=/cdp/**
          filters:
            - name: KeycloakLoginCheckFilter
            - RewritePath=/cdp/(?<segment>.*), /${segment}
        - id: provider
          uri: http://localhost:8086
          predicates:
            - Path=/provider/**
          filters:
            - name: KeycloakLoginCheckFilter
            - RewritePath=/provider/(?<segment>.*), /${segment}
        - id: eureka
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

  # Disable all security auto-configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.reactive.ReactiveOAuth2ResourceServerAutoConfiguration
      

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true

keycloak:
  base-url: http://localhost:8080
  realm: teastore
  client-id: admin-cli
  client-secret: votre-client-secret

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    priam.gateway.priamgateway: DEBUG

  security:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
#spring:
#
#  application:
#    name: gateway
#
#  cloud:
#    gateway:
#      default-filters: []
#        #- TokenRelay
#      routes:
#        - id: data
#          uri: http://localhost:8081
#          predicates:
#            - Path=/data/**
#        - id: actor
#          uri: http://localhost:8082
#          predicates:
#            - Path=/actor/**
#        - id: right
#          uri: http://localhost:8083
#          predicates:
#            - Path=/right/**
#        - id: consent
#          uri: http://localhost:8089
#          predicates:
#            - Path=/consent/**
#        # etc.
#
#
#otel:
#  traces:
#    exporter: otlp
#  exporter:
#    otlp:
#      endpoint: ${JAEGER_ENDPOINT:http://jaeger:4317}
#      protocol: grpc
#  service:
#    name: PRIAM-gateway-Service
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
#  instance:
#    preferIpAddress: true
#
#server:
#  port: 8090
#r2dbc:
#    url: r2dbc:postgresql://localhost:5432/mydatabase
#    username: myuser
#    password: mypassword
#
#keycloak:
#  base-url: http://localhost:8080
#  realm: teastore
#  client-id: admin-cli
#  username: admin
#  password: adminpwd
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.boot.actuate: DEBUG
#    org.springframework.security.oauth2: DEBUG
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,gateways,routes
#
#
