version: '3'
services:
  ##################################################################################################################
  #                     Keycloak and OAuth2 Proxy for Authentication and Authorization                             #
  ##################################################################################################################
  keycloak-db:
    image: postgres:15
    container_name: teastore-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kcpassword
      KC_DB_SCHEMA: public
      KC_DB_SCHEMA_UPDATE: update
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - teastore_kc_net


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: teastore-keycloak
    command: start-dev --cache=local --spi-migration-strategy=UPDATE  --import-realm 
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kcpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpwd

    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    volumes:
      - keycloak-config:/opt/keycloak/data
      - ./keycloak-config:/opt/keycloak/data/import  # ← Montage du dossier local
    restart: unless-stopped
    networks:
      - teastore_kc_net
  ##################################################################################################################

  registry:
  #image: descartesresearch/teastore-registry
    image: registry.gitlab.com/priam3/teastore/teastore-registry
    expose:
      - "8180"
    # depends_on:
    #   - jaeger
    networks:
      - shared_net
  db:
    #image: descartesresearch/teastore-db
    image: registry.gitlab.com/priam3/teastore/teastore-db
    expose:
      - "3306"
    ports:
      - "3307:3306"
    # depends_on:
    #   - jaeger
    networks:
      - shared_net
    volumes:
      - db_data:/var/lib/mysql

  persistence:
    #image: descartesresearch/teastore-persistence
    image: registry.gitlab.com/priam3/teastore/teastore-persistence
    expose:
      - "8180"
    environment:
      HOST_NAME: persistence
      REGISTRY_HOST: registry
      DB_HOST: "db"
      DB_PORT: "3306"

      JAVA_TOOL_OPTIONS: >
        -javaagent:/otel.jar
        -Dotel.traces.exporter=otlp
        -Dotel.exporter.otlp.protocol=grpc
        -Dotel.exporter.otlp.endpoint=http://192.168.1.103::4317
        -Dotel.service.name=persistence-service
        -Dotel.metrics.exporter=none
        -Dotel.logs.exporter=none
    # depends_on:
    #   - jaeger
    networks:
      - shared_net
  auth:
    #image: descartesresearch/teastore-auth
    image: registry.gitlab.com/priam3/teastore/teastore-auth
    #image: teastore-auth
    expose:
      - "8180"
    ports:
      - "8188:8080"
    environment:
      HOST_NAME: auth
      REGISTRY_HOST: registry
      JAVA_TOOL_OPTIONS: >
        -javaagent:/otel.jar
        -Dotel.traces.exporter=otlp
        -Dotel.exporter.otlp.protocol=grpc
        -Dotel.exporter.otlp.endpoint=http://192.168.1.103:4317
        -Dotel.service.name=auth-service
        -Dotel.metrics.exporter=none
        -Dotel.logs.exporter=none

    depends_on:
      - registry
      - keycloak
    networks:
      - shared_net
      - teastore_kc_net      
  image:
    #image: descartesresearch/teastore-image
    image: registry.gitlab.com/priam3/teastore/teastore-image
    expose:
      - "8180"
    environment:
      HOST_NAME: image
      REGISTRY_HOST: registry

      JAVA_TOOL_OPTIONS: >
        -javaagent:/otel.jar
        -Dotel.traces.exporter=otlp
        -Dotel.exporter.otlp.protocol=grpc
        -Dotel.exporter.otlp.endpoint=http://192.168.1.103:4317
        -Dotel.service.name=image-service
        -Dotel.metrics.exporter=none
        -Dotel.logs.exporter=none
    # depends_on:
    #   - jaeger
    networks:
      - shared_net
  recommender:
    #image: descartesresearch/teastore-recommender
    image: registry.gitlab.com/priam3/teastore/teastore-recommender-withoutpriam
    #image: registry.gitlab.com/priam3/teastore/teastore-recommender-with-priam
    expose:
      - "8180"
    environment:
      HOST_NAME: recommender
      REGISTRY_HOST: registry

      JAVA_TOOL_OPTIONS: >
        -javaagent:/otel.jar
        -Dotel.traces.exporter=otlp
        -Dotel.exporter.otlp.protocol=grpc
        -Dotel.exporter.otlp.endpoint=http://192.168.1.103:4317
        -Dotel.service.name=recommender-service
        -Dotel.metrics.exporter=none
        -Dotel.logs.exporter=none
    # depends_on:
    #   - jaeger
    networks:
      - shared_net
  webui:
    #image: descartesresearch/teastore-webui
    image: registry.gitlab.com/priam3/teastore/teastore-webui
    expose:
      - "8180"
    environment:
      HOST_NAME: webui
      REGISTRY_HOST: registry

      JAVA_TOOL_OPTIONS: >
        -javaagent:/otel.jar
        -Dotel.traces.exporter=otlp
        -Dotel.exporter.otlp.protocol=grpc
        -Dotel.exporter.otlp.endpoint=http://192.168.1.103:4317
        -Dotel.service.name=webui-service
        -Dotel.metrics.exporter=none
        -Dotel.logs.exporter=none
    # depends_on:
    #   - jaeger
    ports:
      - "8180:8080"
    networks:
      - shared_net

  ##################################################################################################################
  #                             CAdvisor & Jaeger for tracing request handling                                     #
  ##################################################################################################################
  cadvisor:
    # image: gcr.io/cadvisor/cadvisor:latest
    image: registry.gitlab.com/priam3/teastore/cadvisor
    ports:
      - "8088:8080"
    networks:
      - shared_net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
  #jaeger:
    #image: jaegertracing/all-in-one:latest
    #container_name: jaeger
    #environment:
        #HOST_NAME: jaeger
        #REGISTRY_HOST: registry
        #COLLECTOR_OTLP_ENABLED: true
        #SPAN_STORAGE_TYPE: badger
        #BADGER_EPHEMERAL: "false"
        #BADGER_DIRECTORY_VALUE: /badger/data
        #BADGER_DIRECTORY_KEY: /badger/key
    #ports:
        #- "16686:16686"   # UI
        #- "4317:4317"     # OTLP gRPC
    #command:
        #- "--collector.otlp.enabled=true"
        #- "--collector.otlp.grpc.host-port=0.0.0.0:4317"
    #user: root
    #volumes:
        #- jaeger-data:/badger
    #networks:
        #- shared_net
  
  ##################################################################################################################

volumes:
  keycloak-db-data:
  keycloak-config:  
  db_data:
  jaeger-data:

networks:
  shared_net:
    driver: bridge
    name: shared_net
  teastore_kc_net:
    driver: bridge
    name: teastore_kc_net
    
