spring:

  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

keycloak:
  realm: priam-realm
  resource: Data-client
  bearer-only: true
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  ssl-required: none
  cors: true

otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://jaeger:4317
      protocol: grpc
  service:
    name: PRIAM-Right-Service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8090

