spring:

  application:
    name: gateway


  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         keycloak:
  #           client-id: gateway-client
  #           client-secret: your-client-secret
  #           provider: keycloak
  #           authorization-grant-type: authorization_code
  #           redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  #           scope: openid,profile,email
  #       provider:
  #         keycloak:
  #           issuer-uri: http://localhost:8080/realms/your-realm
  #           user-name-attribute: preferred_username

  cloud:
    gateway:
      default-filters: []
        #- TokenRelay
      routes:
        - id: data
          uri: http://localhost:8081
          predicates:
            - Path=/data/**
        - id: actor
          uri: http://localhost:8082
          predicates:
            - Path=/actor/**
        - id: right
          uri: http://localhost:8083
          predicates:
            - Path=/right/**
        - id: consent
          uri: http://localhost:8089
          predicates:
            - Path=/consent/**
        # etc.


otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: ${JAEGER_ENDPOINT:http://jaeger:4317}
      protocol: grpc
  service:
    name: PRIAM-gateway-Service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8090
r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword

keycloak:
  base-url: http://localhost:8080
  realm: your-realm
  client-id: admin-cli
  username: admin
  password: adminpwd

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateways,routes